Repository 24-AI-Interview/frontend, pull requests merged in 2025-08, with the labels that each got.

#7 Feat: Header CSS Modules + InterviewSession, CategorySelect 페이지 추가 + 레이아웃/스타일 정리
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Common/Button.jsx
  src/components/Common/Button.module.css
  src/components/Common/Header.jsx
  src/components/Common/Header.module.css
  src/components/Common/Input.jsx
  src/components/Common/PageHero.css
  src/components/Common/PageHero.jsx
  src/index.css
  src/index.js
  src/layouts/PageLayout.css
  src/layouts/PageLayout.jsx
  src/logo.svg
  src/pages/Interview/CategorySelect.jsx
  src/pages/Interview/CategorySelect.module.css
  src/pages/Interview/InterviewSessionPage.jsx
  src/pages/Interview/InterviewSessionPage.module.css
  src/pages/InterviewPrep/InterviewPrepPage.jsx
  src/pages/InterviewPrep/InterviewPrepPage.module.css
  src/pages/MyPage/BasicInfoPage.jsx
  src/pages/MyPage/BasicInfoPage.module.css
  src/pages/MyPage/MyPageTabs.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/tokens.css
Labels: 조예인 🍑, Feature ✨, 🔧 작업 중, ❗리뷰 요청

#17 [Refactor] header: 공통 헤더 문구 수정 및 링크 추가
  src/components/Common/Header.jsx
Labels: 나연우 🤍, Refactor ♻️, 🌀 피드백 중

#19 Feat: 얼굴 마스크 및 눈·코·입 가이드라인 추가
  src/pages/Interview/InterviewSessionPage.jsx
  src/pages/Interview/InterviewSessionPage.module.css
Labels: 조예인 🍑, Feature ✨, Refactor ♻️, ✅ 완료

#21 [Feat] AptitudeTestPage: 인적성 검사 페이지 추가 및 라우터 수정
  src/App.js
  src/pages/AptitudeTest/AptitudeTestPage.jsx
  src/pages/AptitudeTest/AptitudeTestPage.module.css
Labels: 나연우 🤍, Feature ✨, ❗리뷰 요청
